name: CI

on:
  push:
    branches: [ main, parallel ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y g++ make libomp-dev libgtest-dev cmake
        cd /usr/src/gtest
        sudo cmake CMakeLists.txt
        sudo make
        sudo cp lib/*.a /usr/lib
        
    - name: Build
      run: make
      
    - name: Run tests
      run: make test && ./run_tests
      
    - name: Test application
      run: |
        echo -e "image.bmp\n5 1.5" | ./image -t 2 