name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y g++ make libomp-dev
        
    - name: Build
      run: make
      
    - name: Test
      run: |
        echo -e "image.bmp\n5 1.5" | ./image -t 2 